### ISSUE TITLE
Subのサンプルで映像が描画されない

### ISSUE THREAD

**Issue by xeno14** [shiguredo/sora-unity-sdk-samples#1]
SoraLaboを利用してRaspberry Pi Zero Wから映像を配信し、サンプルのsubにて受信しようとしましたが、映像が描画されません。
SoraLaboのダッシュボードで見るとdownstreamで接続されています。また、SoraLaboの[シングルストリーム受信](https://sora-labo.shiguredo.jp/recvonly)では正常に映像が受信されています。
どのあたりをデバッグしたらいいか等、アドバイスお願いできますでしょうか。よろしくお願いします。

### Unityのログ
```
Sora is Created: signalingUrl=wss://sora-labo.shiguredo.jp/signaling, channelId=XXX
UnityEngine.Debug:LogFormat(String, Object[])
SoraSample:OnClickStart() (at Assets/SoraSample.cs:336)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2019.2.14f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)

OnAddTrack: trackId=28
UnityEngine.Debug:LogFormat(String, Object[])
SoraSample:<InitSora>b__36_0(UInt32) (at Assets/SoraSample.cs:154)
Sora:TrackCallback(UInt32, IntPtr) (at Assets/SoraUnitySdk/Sora.cs:151)
Sora:sora_dispatch_events(IntPtr)
Sora:DispatchEvents() (at Assets/SoraUnitySdk/Sora.cs:206)
SoraSample:Update() (at Assets/SoraSample.cs:126)

OnNotify: {"audio":true,"channel_connections":3,"channel_downstream_connections":2,"channel_upstream_connections":1,"client_id":"XXX","connection_id":"XXX","event_type":"connection.created","metadata_list":[],"minutes":0,"role":"downstream","turn_transport_type":"udp","type":"notify","video":true}
UnityEngine.Debug:LogFormat(String, Object[])
<>c:<InitSora>b__36_4(String) (at Assets/SoraSample.cs:188)
Sora:NotifyCallback(String, Int32, IntPtr) (at Assets/SoraUnitySdk/Sora.cs:187)
Sora:sora_dispatch_events(IntPtr)
Sora:DispatchEvents() (at Assets/SoraUnitySdk/Sora.cs:206)
SoraSample:Update() (at Assets/SoraSample.cs:126)

```

### Unity
Unity 2019.2.14f1
sora-unity-sdk Release v1.0.4

### Raspberry Pi側環境
Raspberry Pi Zero W (Raspbian GNU/Linux 10 (buster))
momo-19.12.1
```
./momo --no-audio --port 0 --use-native sora \
    wss://sora-labo.shiguredo.jp/signaling XXX@sora-labo \
        --auto --video-codec VP8 --video-bitrate 500 \
        --role sendonly --metadata '{"signaling_key": "XXXXXXXX"}'
```

**Comment by voluntas** [comment]
@xeno14 

- [ ] Momo を最新版 2020.2 で再度確認をお願いします。同様であれば同様だったと書き込んでいただければと思います
- [ ] Raspberry Pi からの映像ではなく Sora Labo のシングルストリーム送信からの確認もお願いします

上記 2 点確認をお願いします。

**Comment by xeno14** [comment]
@voluntas 

- Momo を最新版 2020.2 で再度確認をお願いします
  - 同様でした
- Raspberry Pi からの映像ではなく Sora Labo のシングルストリーム送信での確認をお願いします
  - シングルストリーム送信からカメラ映像を送信したところ、ブラウザでは受信できましたがUnityでは受信できませんでした。送信は同一LAN内の別のPCから行い、Unityが動いてるPC上のブラウザで受信できました。
- Sora Unity SDK サンプルをそのまま利用した場合正常に動作するかの確認をお願いします
  - 現状サンプルのsub.unityでSignaling Url, Channel Id, Signaling Keyのみ指定した状態です。
- Sora unity SDK は Windows と macOS どちらで動作させているか教えて下さい
  - Windows 10 Proです。

**Comment by voluntas** [comment]
@xeno14 確認ありがとうございます。こちらでも再現するか確認してみます。

**Comment by voluntas** [comment]
@xeno14 おそらく受信側のコーデックをデフォルトにしているため接続されないのかなと思いました。Sora はデフォルトで VP9 を使用するため、コーデックの設定を行わないと VP9 を利用します。

配信側が VP8 や H.264 にすると視聴できません。

配信側を VP9 にするか、視聴側のコーデックを配信側に合わせて指定するようにしてください。

**Comment by xeno14** [comment]
@voluntas コーデックを合わせたら無事描画できました。ありがとうございます。
