### ISSUE TITLE
カメラが検出されないとアプリがクラッシュする

### ISSUE THREAD

**Issue by ZioCain** [shiguredo/sora-unity-sdk-samples#11]
こんにちは、
Unityでプラグインを使用してVRアプリケーションを構築していますが、大きな問題に直面しています。
デバイスにカメラ（picoヘッドセットやoculus questヘッドセットなど）がない場合、アプリはエラーメッセージなしでクラッシュします。 どちらのヘッドセットもAndroidをベースにしています。
アプリは常にカメラとマイクの許可を要求するため、許可の問題ではありません。
SoraSample.csスクリプトからUnityカメラキャプチャとオーディオのみを設定しようとしましたが、それでもアプリがクラッシュします。

これを解決する方法はありますか？

問題について話し合う別の方法がある場合は、お知らせください。

**Comment by voluntas** [comment]
Discord で相談がないため、閉じます。
